{
 "title": "KubeVela Multi-Cluster Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "cluster_isconnected{}" } }
  ]
 },
 "panels": [
  { "title": "${cluster}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "Cluster Resource Usage Percent of $cluster",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cluster_cpu_usage{cluster=~\"$cluster\"}/cluster_cpu_allocatable{cluster=~\"$cluster\"}*100",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "cluster_memory_usage{cluster=~\"$cluster\"}/cluster_memory_allocatable{cluster=~\"$cluster\"}*100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Connectivity",
   "type": "stat",
   "description": "Connectivity between the managed cluster and the control plane",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_isconnected{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Cluster CPU resource of ${cluster}",
   "type": "stat",
   "description": "The resource of cpu, unit is m",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_cpu_allocatable{cluster=~\"$cluster\"}",
     "legendFormat": "CPU Allocatable"
    },
    {
     "expr": "cluster_cpu_capacity{cluster=~\"$cluster\"}",
     "legendFormat": "CPU Capacity"
    },
    {
     "expr": "cluster_cpu_usage{cluster=~\"$cluster\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Cluster Memory resource of ${cluster}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_memory_allocatable{cluster=~\"$cluster\"}",
     "legendFormat": "Memory Allocatable"
    },
    {
     "expr": "cluster_memory_capacity{cluster=~\"$cluster\"}",
     "legendFormat": "Memory Capacity"
    },
    {
     "expr": "cluster_memory_usage{cluster=~\"$cluster\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Cluster Pod Allocatable of $cluster",
   "type": "stat",
   "description": "The number of pod Allocatable/Capacity",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_pod_allocatable{cluster=~\"$cluster\"}",
     "legendFormat": "Pod Allocatable"
    },
    {
     "expr": "cluster_pod_capacity{cluster=~\"$cluster\"}",
     "legendFormat": "Pod Capacity"
    },
    {}
   ]
  },
  {
   "title": "Cluster CPU Panel of $cluster",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cluster_cpu_allocatable{cluster=~\"$cluster\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cluster_cpu_usage{cluster=~\"$cluster\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Panel of $cluster",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cluster_memory_allocatable{cluster=~\"$cluster\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cluster_memory_usage{cluster=~\"$cluster\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}